dist: trusty
install: true
language: java
jdk:
    - oraclejdk8

env: DISPLAY=:99.0

before_install:
    - sudo apt-get install at-spi2-core

before_script:
    - sh -e /etc/init.d/xvfb start
    - sleep 10 # give xvfb some time to start

script: mvn -f mavendeps/pom.xml p2:site && mvn clean verify

after_failure:
    - cat $TRAVIS_BUILD_DIR/tests/org.codechecker.eclipse.rcp.it.tests/target/work/data/.metadata/.log
    - cat $TRAVIS_BUILD_DIR/tests/org.codechecker.eclipse.rcp.it.tests/target/surefire-reports/*

