
sudo: required

dist: trusty

language: java

jdk:
    - oraclejdk7

addons:
    apt:
        package:
            maven
            tar

before_script:
    - cd ../;curl http://www-eu.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz | tar zx
    - cd thrift-0.9.3
    - ./configure --with-c_glib=yes --with-ruby=no
    - make
    - export PATH=$PATH:$PWD/compiler/cpp/
    - cd ../CodeCheckerEclipsePlugin/eclipse-plugin/

script: mvn install; mvn clean test

